url: https://test.samalik.com
title: "Adam's Blog"
name: 'Adam Samalik'
locale: "en-GB"
description: >
  Open Source, Open Mind, Open Ideas, Open
  Everything.

plugins:
  - jekyll-include-cache
 
remote_theme: "mmistakes/minimal-mistakes@4.14.2"

minimal_mistakes_skin: "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum" "sunrise"
breadcrumbs: false
paginate: 5 # amount of posts to show
paginate_path: /page:num/

author:
  name     : "Adam Šamalík"
  avatar   : "/assets/images/profile-pic.jpeg"
  bio      : "Open source enthusiast. Software Engineer with Red Hat working on Fedora. Design is not just how it looks like."
  location : "Prague, CZ" 
  links:
  - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/adsamalik"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: false
      read_time: true
      comments: false
      share: false
      related: false
