url: https://test.samalik.com
name: 'Adam&#039;s Blog'
description: >
  Open Source, Open Mind, Open Ideas, Open
  Everything.

plugins:
  - jekyll-include-cache
 
remote_theme: "mmistakes/minimal-mistakes@4.14.2"
